### ISSUE TITLE
[FEATURE] TagPathParser

### ISSUE THREAD

**Issue by cosminroger** [ignition-api/8.1#104]
**Is your feature request related to a problem? Please describe.**
For one of the projects, TagPathParser is needed since the path of a tag is important for subsequent modifications of other references.

**Describe the solution you'd like**
Adding the TagPathParser function from https://files.inductiveautomation.com/sdk/javadoc/ignition81/8.1.21/com/inductiveautomation/ignition/common/tags/paths/parser/TagPathParser.html#%3Cinit%3E()

**Comment by thecesrom** [comment]
Hello, @cosminroger.

Thanks for submitting a feature request. I have added the `TagPathParser` class as well as supporting classes.

Expect a release by Friday.
