### ISSUE TITLE
[FEATURE] how to get the value of tag 

### ISSUE THREAD

**Issue by xiahui1986** [ignition-api/8.1#259]
I write code like this 
  tagR = system.tag.readBlocking(['[default]xxx/xxx/xxx/xxx'])
  tagR0=tagR[0]
  testValue =tagR0.getValue()
  print(tagR0.getValue())
but I get the value is java.lang.object  ,how to convert it to the python base type ?

**Comment by thecesrom** [comment]
Hello @xiahui1986,

Since the purpose of this library is to allow code completion, it does not provide the same functionality as running the code on the Ignition Designer or Script Console.

Hopefully this solves your question.
